//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//************************
//Created by Nathan Bowden
//October 9, 2014
//************************
//
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Player_Stealthed : MonoBehaviour 
{
	public bool isLit = false;
    public bool isPigAlert = false;
    public GUITexture litHUD;
    public GUITexture alertHUD;

    private object[] pigObjects;

    void Start()
    {
        this.renderer.material.color = new Color(1f, 1f, 1f, 0.5f);

    }

	//Update is called once per frame
	void Update() 
	{
        pigObjects = GameObject.FindGameObjectsWithTag("Enemy");
        foreach ( object current in pigObjects )
        {
            GameObject currentPig = (GameObject) current;
            if ( currentPig.GetComponent<AIControllerPatrolPig>().m_canSeePlayer )
            {
                isPigAlert = true;
                break;
            }

            isPigAlert = false;
        }

        if (isPigAlert)
        {
            Physics2D.IgnoreLayerCollision(8, 19, false);
            litHUD.enabled = false;
            alertHUD.enabled = true;
        }
        else if ( isLit )
        {
            Physics2D.IgnoreLayerCollision(8, 19, false);
            /*stealthedHUD.enabled = false;*/
            litHUD.enabled = true;
            //litScreenHUD.enabled = false;
        }
        else
        {
            Physics2D.IgnoreLayerCollision(8, 19, true);
            /*stealthedHUD.enabled = true;*/
            litHUD.enabled = false;
            alertHUD.enabled = false;
            //litScreenHUD.enabled = true;
        }

	}

    void OnTriggerEnter2D( Collider2D otherCollider )
    {
        if ( otherCollider.gameObject.tag == "Lantern" )
        {
            isLit = true;
            this.renderer.material.color = new Color(1f, 1f, 1f, 1f);
        }
    }

    void OnTriggerStay2D( Collider2D otherCollider )
    {
        if ( otherCollider.gameObject.tag == "Lantern" )
        {
            isLit = true;
            this.renderer.material.color = new Color(1f, 1f, 1f, 1f);
        }
    }

    void OnTriggerExit2D( Collider2D otherCollider )
    {
        if ( otherCollider.gameObject.tag == "Lantern" )
        {
            isLit = false;
            this.renderer.material.color = new Color(1f, 1f, 1f, 0.5f);
        }
    }

}


